### ISSUE TITLE
Builds Failing

### ISSUE THREAD

**Issue by ghoshbishakh** [NIT-dgp/festcms#125]
https://travis-ci.org/NIT-dgp/festcms/jobs/235920360

```
requests-oauthlib, python3-openid, python-social-auth, PyUnusedCodeBear, SpaceConsistencyBear

  Found existing installation: appdirs 1.4.3

    Uninstalling appdirs-1.4.3:

      Successfully uninstalled appdirs-1.4.3

  Rolling back uninstall of appdirs

Exception:

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2813, in _dep_map

    return self.__dep_map

  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2624, in __getattr__

    raise AttributeError(attr)

AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2804, in _parsed_pkg_info

    return self._pkg_info

  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2624, in __getattr__

    raise AttributeError(attr)

AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main

    status = self.run(options, args)

  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run

    prefix=options.prefix_path,

  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install

    **kwargs

  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/pip/req/req_install.py", line 851, in install

    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)

  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files

    isolated=self.isolated,

  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/pip/wheel.py", line 247, in move_wheel_files

    prefix=prefix,

  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/pip/locations.py", line 140, in distutils_scheme

    d = Distribution(dist_args)

  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/setuptools/dist.py", line 321, in __init__

    _Distribution.__init__(self, attrs)

  File "/opt/python/3.5.3/lib/python3.5/distutils/dist.py", line 281, in __init__

    self.finalize_options()

  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/setuptools/dist.py", line 389, in finalize_options

    ep.require(installer=self.fetch_build_egg)

  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2324, in require

    items = working_set.resolve(reqs, env, installer, extras=self.extras)

  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 862, in resolve

    new_requirements = dist.requires(req.extras)[::-1]

  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2568, in requires

    dm = self._dep_map

  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2815, in _dep_map

    self.__dep_map = self._compute_dependencies()

  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2824, in _compute_dependencies

    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:

  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2806, in _parsed_pkg_info

    metadata = self.get_metadata(self.PKG_INFO)

  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1468, in get_metadata

    value = self._get(self._fn(self.egg_info, name))

  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1577, in _get

    with open(path, 'rb') as stream:

FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/appdirs-1.4.3.dist-info/METADATA'

The command "pip install -r dev-requirements.txt" failed and exited with 2 during .

Your build has been stopped.
```

**Comment by ghoshbishakh** [comment]
@nkprince007 any idea?

**Comment by nkprince007** [comment]
That's a coala dependency issue. I'll fix that in the evening. Caught up in work right now.

**Comment by ghoshbishakh** [comment]
@nkprince007 great! Thanks!

**Comment by ghoshbishakh** [comment]
@nkprince007 YAY!! 
![image](https://user-images.githubusercontent.com/5156787/27001602-f09954ae-4deb-11e7-97ef-1031b8c35a4f.png)
